quarkus.application.name=client-service
quarkus.http.port=8083

quarkus.hibernate-orm.database.generation=update


# OpenAPI / Swagger
quarkus.swagger-ui.always-include=true

# Health checks (Kubernetes)
quarkus.smallrye-health.root-path=/q/health

#DB config
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/client
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
