quarkus.application.name=product-service
quarkus.http.port=8080

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql


# OpenAPI / Swagger
quarkus.swagger-ui.always-include=true

# Health checks (Kubernetes)
quarkus.smallrye-health.root-path=/q/health

#DB config
#quarkus.datasource.jdbc.url=jdbc:postgresql:///postgres:5432/products
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres


quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm".level=DEBUG
quarkus.hibernate-orm.log.sql=true
